[workspace]
members = [
    "crates/tuneweave-core",
    "crates/tuneweave-provider-bilibili",
    "crates/tuneweave-provider-kugou",
    "crates/tuneweave-provider-kuwo",
    "crates/tuneweave-provider-migu",
    "crates/tuneweave-provider-netease",
    "crates/tuneweave-provider-qq",
    "crates/tuneweave-provider-soda",
    "crates/tuneweave-server",
]
default-members = ["crates/tuneweave-server"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.8"
authors = ["MOPELotus"]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MOPELotus/TuneWeave"

[workspace.dependencies]
async-trait = "0.1.89"
aes = "0.8.4"
aws-lc-rs = "1.17.1"
axum = { version = "0.8.9", default-features = false, features = ["http1", "json", "matched-path", "multipart", "query", "tokio"] }
base64 = "0.22.1"
bytes = "1.12.1"
cbc = "0.1.2"
ecb = "0.1.2"
encoding_rs = "0.8.35"
flate2 = "1.1.9"
futures-util = { version = "0.3.32", default-features = false, features = ["sink"] }
hex = "0.4.3"
lofty = { version = "0.24.0", default-features = false }
md-5 = "0.10.6"
num-bigint = "0.4.6"
percent-encoding = "2.3.2"
qrcode = { version = "0.14.1", default-features = false, features = ["svg"] }
rand = "0.10.2"
reqwest = { version = "0.13.4", default-features = false, features = ["brotli", "deflate", "form", "gzip", "json", "query", "rustls"] }
rumqttc = { version = "0.25.1", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha1 = "0.11.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = { version = "0.30.0", default-features = false, features = ["handshake"] }
tower = { version = "0.5.3", features = ["util"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["chrono", "env-filter", "json"] }
tuneweave-core = { path = "crates/tuneweave-core" }
tuneweave-provider-bilibili = { path = "crates/tuneweave-provider-bilibili" }
tuneweave-provider-kugou = { path = "crates/tuneweave-provider-kugou" }
tuneweave-provider-kuwo = { path = "crates/tuneweave-provider-kuwo" }
tuneweave-provider-migu = { path = "crates/tuneweave-provider-migu" }
tuneweave-provider-netease = { path = "crates/tuneweave-provider-netease" }
tuneweave-provider-qq = { path = "crates/tuneweave-provider-qq" }
tuneweave-provider-soda = { path = "crates/tuneweave-provider-soda" }
url = "2.5.8"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
