[package]
name = "tuneweave-provider-migu"
description = "Migu Music provider for TuneWeave"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tuneweave-core.workspace = true
url.workspace = true

[lints]
workspace = true
